### ISSUE TITLE
Remove type attribute from iframe

### ISSUE THREAD

**Issue by Aybee** [fritzmg/contao-youtube-iframe#4]
https://github.com/fritzmg/contao-youtube-iframe/blob/master/system/modules/youtube_iframe/templates/c35/ce_player.html5#L8

This throws a validation error
> Error: Attribute “type” not allowed on element “iframe” at this point.

**Comment by fritzmg** [comment]
Yeah, this was used in the old iframe embed code of YouTube. But it has been removed now. See https://stackoverflow.com/questions/4800227/why-did-youtube-put-a-type-attribute-in-iframe-for-embedded-video for instance.

I'll change it accordingly.

**Comment by Aybee** [comment]
Thank you. I think this has a priority of -99. But its always nice to see no errors while validating a page 😉

**Comment by fritzmg** [comment]
Done in `2.2.0`. However I re-added the `frameborder="0"` attribute, to be in sync with Contao 4's current `ce_youtube` template.

Version `2.2.0` also adds true Contao 4 support.

**Comment by Aybee** [comment]
Why this? Frameborder is only for HTML4. It has to be removed in Contao 4.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-frameborder

**Comment by fritzmg** [comment]
Agreed. I have removed it again. I also created a PR for the core-bundle: https://github.com/contao/core-bundle/pull/1233

**Comment by Aybee** [comment]
Many thanks again. Your're the best 🥇
