### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by fiedsch** [fritzmg/contao-youtube-iframe#5]
Führt das 
```php
<?php $this->extend('ce_player'); ?>
```
in `ce_player.html5` nicht zu einer endlosen Rekursion ("ich bin mein eigener parent")?

Ich habe die Erweiterung selbst nicht im Einsatz, aber siehe https://community.contao.org/de/showthread.php?69230-Contao-Version-nur-LTS-Versionen&p=460345&viewfull=1#post460345

**Comment by fritzmg** [comment]
Hm, soweit ich mich erinnere sollte das funktionieren, aber evt. nur im templates Ordner und nicht bei Templates von Extensions. Ich werde das nochmal prüfen.. aber leider erst im neuen Jahr ;)

**Comment by fiedsch** [comment]
Danke und ruhige Feiertage!

**Comment by fritzmg** [comment]
Fixed in 2.2.4
