### ISSUE TITLE
Option für DSGVO-konforme Einbettung integrieren?

### ISSUE THREAD

**Issue by planepix** [fritzmg/contao-youtube-iframe#6]
Hallo Fritz,

im Zug von Anpassungen für die DSGVO bietet YouTube die Option, die Einbindung in die eigene Website DSGVO-konform einzubetten.

Denkbar, dass das in einem Update ergänzt werden kann?

Infolink:
https://www.schieb.de/757515/dsgvo-youtube-videos-korrekt-einbetten

Beste Grüße
Thomas

**Comment by fritzmg** [comment]
Der Unterschied ist, dass bei aktivierter Option die Domain `www.youtube-nocookie.com` verwendet wird und ansonsten die Domain `www.youtube.com`.

Ob das im Sinne der DSVGO für alle Beteiligten reicht kann ich nicht beurteilen. Aber gibt es einen Grund _nicht_ die youtube-nocookie.com Domain zu verwenden? Wenn nicht würde ich das nicht optional implementieren sondern die Domain einfach direkt ändern. Falls man doch die `youtube.com` Domain (in Contao 3) haben möchte, kann man sich ja ein eigenes `ce_player` Template machen.

Unter Contao 4 muss es sowieso im Core geändert werden.

**Comment by fritzmg** [comment]
Related: https://github.com/contao/core-bundle/pull/1463

**Comment by fritzmg** [comment]
d77f9cd
