### ISSUE TITLE
Confirmation overlay

### ISSUE THREAD

**Issue by fritzmg** [fritzmg/contao-youtube-iframe#7]
See https://github.com/contao/core-bundle/issues/1512#issuecomment-386219407

/cc @netzarbeiter

**Comment by frontendschlampe** [comment]
@fritzmg Hättest du Interesse diesen Punkt ggfs. hier einzubauen? https://github.com/friends-of-contao/contao-privacy :-)

Dann haben wir eine gesammelte Privacy Extension :-)

**Comment by fritzmg** [comment]
Ja, vielleicht kann ich da am Wochenende daran arbeiten :)

**Comment by frontendschlampe** [comment]
Du bist ein guter. Wenn du willst, kann ich Dich zum Repo adden :-)

**Comment by fritzmg** [comment]
Ja, also ich würde es eh zuerst mal als PR machen, um den Vorschlag zu diskutieren :). Gibt ja mehrere Möglichkeiten und Ausbaustufen.

**Comment by frontendschlampe** [comment]
wie du willst ... kannst auch einen eigenen Branch machen im Repo ... kein Ding

**Comment by fritzmg** [comment]
https://github.com/friends-of-contao/contao-privacy/pull/14
