### ISSUE TITLE
[Idee] externes Thumbnail von youtube lokal speichern

### ISSUE THREAD

**Issue by akroii** [fritzmg/contao-youtube-iframe#8]
Nur eine Idee, weil nicht jeder für jedes Video ein Thumbnail erstellen will. Wäre es nicht eine Idee Wert das Thumbnail von Youtube in den Bild Cache zu schreiben?
Also: `https://img.youtube.com/vi/YOUTUBEID/mqdefault.jpg` in die `assets` verschieben?

**Comment by fritzmg** [comment]
Falsches repository? Diese Extension hat ja gar keine Möglichkeit dafür ;). Vielleicht meinst du eher das: https://github.com/friends-of-contao/contao-privacy/issues/28
