### ISSUE TITLE
Wrong template with contao-privacy

### ISSUE THREAD

**Issue by Aybee** [fritzmg/contao-youtube-iframe#9]
Contao 4.4.36
contao-privacy ^2.0@beta
contao-youtube-iframe ^2.

Hallo Fritz,

ich bin jetzt total durcheinander. Ich wollte **youtube-iframe** wegen der Parameter und dem responsive CSS und **privacy** wegen des Splashs und dem DSGVO. Jetzt stelle ich aber fest, dass in dieser Konstellation das Template von privacy nicht genommen wird, sonder das von youtube-iframe.

Und wenn das von privacy genommen würde, hätte ich auch nicht den Wrapper und nicht die Parameter.

Ich weiß, du wolltest hier nichts mehr dran machen, aber bis zur nächsten LTS sind es ja noch über ein Jahr (4.9 August 2020), aber wie handeln das die anderen denn? Ich habe mir jetzt ein Template-Mix aus beiden Erweiterungen erstellt, aber das ist ja keine out of the box Lösung.

Wie sieht das ganze bei der nächsten LTS aus?

Mal sehen, ob ich bei privacy noch ein Ticket erstelle, dass das privacy Template erweitert wird. Aber selbst dann wird ja das von youtube-iframe genommen. Könntest du in dem Template prüfen, ob privacy installiert ist und wenn ja, in dem Template das von privacy includen?

**Comment by fritzmg** [comment]
Wie schon in https://github.com/friends-of-contao/contao-privacy/issues/47 erwähnt, musst du ein eigenes `ce_youtube` Template erzeugen und dort die Templates zusammenführen. Einen anderen Weg gibt es in solchen Fällen nicht.
